### ISSUE TITLE
Tests failed on windows

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/asciidoctor-rfc#108]
https://github.com/metanorma/asciidoctor-rfc/commit/a0b21ded98cc97a802b0256ff5562bcc67844ce9/checks?check_suite_id=370754305

**Comment by ronaldtse** [comment]
@CAMOBAP795 this gem is now deprecated in favor of [metanorma-ietf](https://github.com/metanorma/metanorma-ietf/), so it is no longer maintained. Thanks!

Closing.

**Comment by CAMOBAP** [comment]
@ronaldtse I propose to do "Settings -> "Archive this repository" to make this repo read-only

In this case, it will be clear for everyone that it's deprecated/not-maintained anymore

P.S. I haven't permissions to do this
